### ISSUE TITLE
failed to convert html table to docx

### ISSUE THREAD

**Issue by demiwang1214** [pqzx/html2docx#1]
convert html table to docx, but got error as below.
html table is from tinymce

html='<p><table style="border-collapse: collapse; width: 15.9812%;" border="1"><tbody><tr><td style="width: 49.9572%;">rgerh</td><td style="width: 42.9372%;">hyww</td></tr><tr><td style="width: 49.9572%;">wy4y</td><td style="width: 42.9372%;">45e4y</td></tr><tr><td style="width: 49.9572%;">wy4y</td><td style="width: 42.9372%;">45e4y</td></tr><tr><td style="width: 49.9572%;">wy4y</td><td style="width: 42.9372%;">45e4y</td></tr></tbody></table></p>'
new_parser = HtmlToDocx()
new_parser.add_html_to_document(html, docx)
error:
  File "/Users/xxxx/xxxx/venv/lib/python3.6/site-packages/htmldocx/__init__.py", line 215, in handle_table
    rows, cols = self.get_table_dimensions(table_soup)
  File "/Users/xxxxx/xxxxx/venv/lib/python3.6/site-packages/htmldocx/__init__.py", line 369, in 
get_table_dimensions
    cols = rows[0].find_all(['th', 'td'], recursive=False)
IndexError: list index out of range
 def get_table_dimensions(self, table_soup):
        rows = table_soup.find_all('tr', recursive=False). # error : get 'tr', but return rows is []
        cols = rows[0].find_all(['th', 'td'], recursive=False)
        return len(rows), len(cols)

can anyone help me?
thanks

**Comment by pqzx** [comment]
Currently tables with `<tbody>` aren't supported. For now I'd suggest using a workaround of removing the tbody tags from the html before feeding it to add_html_to_document(). E.g.

```
html = re.sub('</*tbody>', '', html)
new_parser.add_html_to_document(html, docx)
```

(The way this whole package is managed is pretty terrible. I'm looking at cleaning that up first before adding a fix).

**Comment by demiwang1214** [comment]
@pqzx 
thank you for response.
i added your workaround, no exception happen now, but the table inline styles didn't display properly, such as table border and cell width didn't display, can it be improved? do you have any suggestion?

![image](https://user-images.githubusercontent.com/72655572/95702008-b5794100-0c7d-11eb-9ae6-c540f1c340a5.png)

**Comment by pqzx** [comment]
This isn't currently supported. Could be worth adding.

https://python-docx.readthedocs.io/en/latest/api/table.html#docx.table.Table
https://python-docx.readthedocs.io/en/latest/api/table.html#docx.table._Column
