### ISSUE TITLE
Issue with float margins and named (vs RGB) colors

### ISSUE THREAD

**Issue by jeromegit** [pqzx/html2docx#10]
Hi, thanks for your library that comes in a very opportune time for me since that's exactly what I needed for my project!
I wanted to report a couple of issues where the library chokes, i.e. throws an exception.
`            margin = int(re.sub(r'[a-z]+', '', margin))
`
which can be fixed with
`            margin = int(float(re.sub(r'[a-z]+', '', margin)))
`
And
`colors = [int(x) for x in color.split(',')]
`
which doesn't support named colors such as "black" or "white". See https://en.wikipedia.org/wiki/Web_colors#Extended_colors for an exhaustive list.

**Comment by pqzx** [comment]
Hey @jeromegit , thanks for picking up these issues. I've added a PR #11 to stop the choking, but supporting proper conversion will take a bit more work.

**Comment by jeromegit** [comment]
Thanks, @pqzx !
