### ISSUE TITLE
HTML Tag <a href=...

### ISSUE THREAD

**Issue by BuriKizilkaya** [pqzx/html2docx#15]
When I call the method parse_html_string with the argument `<a href="https://de.wikipedia.org/wiki/Benutzerschnittstelle#Kennzeichnungen" style="box-sizing:border-box;text-decoration:underline;cursor:pointer;font-family:Arial, sans-serif;font-size:10pt;">https://de.wikipedia.org/wiki/Benutzerschnittstelle#Kennzeichnungen</a>`
, the tag "<a href=..." is not parsed correctly. It is not present in the paragraphs list.

**Comment by jongracecox** [comment]
I tested using your HTML string and the document appears to render correctly.

The code I used was:

```python
html = '<a href="https://de.wikipedia.org/wiki/Benutzerschnittstelle#Kennzeichnungen" style="box-sizing:border-box;text-decoration:underline;cursor:pointer;font-family:Arial, sans-serif;font-size:10pt;">https://de.wikipedia.org/wiki/Benutzerschnittstelle#Kennzeichnungen</a>'
doc = d.parse_html_string(html)
doc.save("issue.doc")
```

The result was: 

> ![image](https://user-images.githubusercontent.com/30441316/126811065-926d6fbb-b0f9-4de9-aa54-c72160bffa56.png)

Can you provide more detail on your issue?

**Comment by karthik-atos** [comment]
Is there way to get any formatting on the hyperlink , underline, or color, because in generated document, there is no way to differentiate a word that is infact a hyperlink.

the test html in this project even that when converted does not display the link like a hyperlink. it looks like any plain text.
