### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Jalkhov** [pqzx/html2docx#6]
The following html code give me above error:

[FILE.txt](https://github.com/pqzx/html2docx/files/6032449/FILE.txt)

**Comment by rmerren** [comment]
I'm getting the same error. The problem seems to be the use of THEAD and TBODY tags. Here is a minimal example...the first HTML with no table head or body tags generates html fine. The second generates the error.

```
#!/usr/bin/env python3

from docx import Document
from htmldocx import HtmlToDocx

parser = HtmlToDocx()

without_header = """
<p>This is a table</p>
<table>
<tr>
<td>Language</td>
<td>1</td>
<td>2</td>
</tr>
<tr>
<td>English</td>
<td>One</td>
<td>One</td>
</tr>
<tr>
<td>Espa&ntilde;ol</td>
<td>Uno</td>
<td>Dos</td>
</tr>
</table>"""

document1 = Document()
parser.add_html_to_document(without_header, document1)
document1.save("without_header.docx")
print("Document 1 created")

with_header = """
<p>This is a table</p>
<table>
<thead>
<tr>
<th>Language</th>
<th>1</th>
<th>2</th>
</tr>
</thead>
<tbody>
<tr>
<td>English</td>
<td>One</td>
<td>One</td>
</tr>
<tr>
<td>Espa&ntilde;ol</td>
<td>Uno</td>
<td>Dos</td>
</tr>
</tbody>
</table>"""

document2 = Document()
parser.add_html_to_document(with_header, document2)
document2.save("with_header.docx")
print("Document 2 created")
```

**Comment by amthorn** [comment]
I ran into this issue myself. I fixed it in this PR: https://github.com/pqzx/html2docx/pull/7

**Comment by wyysoft** [comment]
If <td> has 'colspan' attribute, the code still runs into "IndexError: list index out of range"

**Comment by shourav9884** [comment]
> If has 'colspan' attribute, the code still runs into "IndexError: list index out of range"

Any solution yet?

**Comment by pwsutherland** [comment]
I am able to convert html files with `colspan` attribute without issue. 

So far, when I hit an IndexError I have reviewed my html files and found something funky like `table` tags that do not have content.
